/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false` (hash: b179bcb3f33988e10abaa03de0c9caf1)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces:
			| "NeuralRateMcpAgent"
			| "NeuralRateReadonlyMcpAgent"
			| "NeuralRateConfigMcpAgent"
			| "NeuralRateBenchmarkMcpAgent"
			| "NeuralRateExecutionMcpAgent";
	}
	interface Env {
		CACHE_KV: KVNamespace;
		DECISIONS_DB: D1Database;
		EXECUTOR_BASE_URL: string;
		FRED_API_KEY: string;
		INTERNAL_API_TOKEN: string;
		NANSEN_API_KEY: string;
		NEURALRATE_BENCHMARK_CONTRACT: string;
		NEURALRATE_EXECUTION_GUARD_CONTRACT: string;
		NEURALRATE_POLICY_REGISTRY_CONTRACT: string;
		NEURALRATE_SAFE_4337_MODULE_ADDRESS: string;
		NEURALRATE_SAFE_7579_ADAPTER_ADDRESS: string;
		NEURALRATE_SAFE_7579_LAUNCHPAD_ADDRESS: string;
		NEURALRATE_DELEGATE_VALIDATOR_ADDRESS: string;
		NEURALRATE_4337_ENTRYPOINT_ADDRESS: string;
		NEURALRATE_ERC7484_REGISTRY_ADDRESS: string;
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").NeuralRateMcpAgent>;
		MCP_READONLY_OBJECT: DurableObjectNamespace<import("./src/index").NeuralRateReadonlyMcpAgent>;
		MCP_CONFIG_OBJECT: DurableObjectNamespace<import("./src/index").NeuralRateConfigMcpAgent>;
		MCP_BENCHMARK_OBJECT: DurableObjectNamespace<import("./src/index").NeuralRateBenchmarkMcpAgent>;
		MCP_EXECUTION_OBJECT: DurableObjectNamespace<import("./src/index").NeuralRateExecutionMcpAgent>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EXECUTOR_BASE_URL" | "FRED_API_KEY" | "INTERNAL_API_TOKEN" | "NANSEN_API_KEY" | "NEURALRATE_BENCHMARK_CONTRACT" | "NEURALRATE_EXECUTION_GUARD_CONTRACT" | "NEURALRATE_POLICY_REGISTRY_CONTRACT" | "NEURALRATE_SAFE_4337_MODULE_ADDRESS" | "NEURALRATE_SAFE_7579_ADAPTER_ADDRESS" | "NEURALRATE_SAFE_7579_LAUNCHPAD_ADDRESS" | "NEURALRATE_DELEGATE_VALIDATOR_ADDRESS" | "NEURALRATE_4337_ENTRYPOINT_ADDRESS" | "NEURALRATE_ERC7484_REGISTRY_ADDRESS">> {}
}
