/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false` (hash: b179bcb3f33988e10abaa03de0c9caf1)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "NeuralRateMcpAgent";
	}
	interface Env {
		CACHE_KV: KVNamespace;
		DECISIONS_DB: D1Database;
		FRED_API_KEY: string;
		NANSEN_API_KEY: string;
		NEURALRATE_BENCHMARK_CONTRACT: string;
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").NeuralRateMcpAgent>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FRED_API_KEY" | "NANSEN_API_KEY" | "NEURALRATE_BENCHMARK_CONTRACT">> {}
}
